version: '3.8'

services:
  helperu-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # Stripe Configuration
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_PREMIUM_PRICE_ID=${STRIPE_PREMIUM_PRICE_ID}
      
      # OpenPhone Configuration
      - OPENPHONE_API_KEY=${OPENPHONE_API_KEY}
      - OPENPHONE_FROM_NUMBER=${OPENPHONE_FROM_NUMBER}
      
      # AI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # Apple Bundle IDs 
      - HELPER_MOBILE_APP_BUNDLE_ID=${HELPER_MOBILE_APP_BUNDLE_ID}
      - HELPER_PUSH_NOTIFICATION_P8_ID=${HELPER_PUSH_NOTIFICATION_P8_ID}
      - PUSH_TOKEN_SECRET=${PUSH_TOKEN_SECRET}
      
      # Environment
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
